services:
  - type: web
    name: n8n
    env: docker
    region: frankfurt # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    branch: main # optional (defaults to master)
    # dockerCommand: ./webdis.sh # optional (defaults to Dockerfile command)
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: POSTGRES_HOST
        fromDatabase:
          name: n8nDB
          property: host
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: n8nDB
          property: database
      - key: POSTGRES_PORT
        fromDatabase:
          name: n8nDB
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: n8nDB
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: n8nDB
          property: password
    disk:
      name: n8nDisk
      mountPath: /home/node/.n8n
      sizeGB: 10

databases:
  - name: n8nDB
    plan: starter
