services:
  - type: web
    name: n8n
    env: docker
    region: frankfurt
    plan: standard
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8nDB
          property: host
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8nDB
          property: database
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8nDB
          property: port
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8nDB
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8nDB
          property: password
      - key: DB_TYPE
        value: postgresdb
      - key: N8N_ENCRYPTION_KEY
        value: "gIH4B**7Xf2CDm4SIsmvc2"
      - key: GENERIC_TIMEZONE
        value: "Europe/Berlin"
      - key: WEBHOOK_URL
        value: "https://app.readyformars.org/"
      - key: N8N_LOG_LEVEL
        value: "verbose"
    disk:
      name: n8nDisk
      mountPath: /home/node/.n8n
      sizeGB: 10

databases:
  - name: n8nDB
    plan: starter
